export const SEX = ["Male", "Female"];

export const INDUSTRIES = [
  "Business",
  "Consulting",
  "Education & Training",
  "Engineering",
  "Entertainment",
  "Finance",
  "Healthcare & Medical",
  "Human Resources",
  "Legal Services",
  "Marketing",
  "Nonprofit",
  "Public Administration",
  "Research",
  "Software & Technology",
  "Sports & Recreation"
];

export const EXPERIENCE = [
  "Intern",
  "Junior",
  "Mid-Level",
  "Senior",
  "Manager",
  "Director"
];

export const SALARIES = [
  "20,000 - 25,000",
  "25,000 - 30,000",
  "30,000 - 35,000",
  "35,000 - 40,000",
  "40,000 - 45,000",
  "45,000 - 50,000",
  "50,000 - 55,000",
  "55,000 - 60,000",
  "60,000 - 65,000",
  "65,000 - 70,000",
  "70,000 - 75,000",
  "75,000 - 80,000",
  "80,000 - 85,000",
  "85,000 - 90,000",
  "90,000 - 95,000",
  "95,000 - 100,000",
  "100,000+"
];

export const CURRENCIES = ["GBP", "EUR", "CHF", "DKK", "SEK"];

export const EDUCATION = [
  "High School",
  "Bachelors",
  "Postgraduate Degree",
  "Masters",
  "PHD"
];

export const MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December"
];

export const YEARS = Array.from(
  { length: new Date().getFullYear() - 1979 },
  (_, i) => (1980 + i).toString()
).reverse();

export const JOB_BOARDS = [
  "LinkedIn",
  "Indeed",
  "Reed",
  "Xing",
  "Company website/career page",
  "Refferal",
  "Other"
];

export const COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo, Democratic Republic of the",
  "Congo, Republic of the",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, North",
  "Korea, South",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe"
];

export const COUNTRIES_AND_CITIES = [
  {
    country: "Denmark",
    cities: [
      "Copenhagen",
      "Aarhus",
      "Odense",
      "Aalborg",
      "Esbjerg",
      "Randers",
      "Kolding",
      "Horsens",
      "Vejle",
      "Roskilde"
    ]
  },
  {
    country: "France",
    cities: [
      "Bordeaux",
      "Cannes",
      "Lille",
      "Lyon",
      "Marseille",
      "Montpellier",
      "Nice",
      "Paris",
      "Toulouse",
      "Strasbourg"
    ]
  },
  {
    country: "Germany",
    cities: [
      "Berlin",
      "Hamburg",
      "Munich",
      "Cologne",
      "Frankfurt",
      "Leipzig",
      "Dortmund",
      "Essen",
      "Stuttgart",
      "Düsseldorf",
      "Bremen",
      "Hannover"
    ]
  },
  {
    country: "Ireland",
    cities: [
      "Armagh",
      "Carlow",
      "Cork",
      "Derry",
      "Dublin",
      "Dundalk",
      "Galway",
      "Kilkenny",
      "Limerick",
      "Loughrea",
      "Naas",
      "Sligo",
      "Waterford",
      "Wexford"
    ]
  },
  {
    country: "Netherlands",
    cities: [
      "Almere",
      "Amsterdam",
      "Eindhoven",
      "Groningen",
      "The Hague (Den Haag)",
      "Leiden",
      "Nijmegen",
      "Rotterdam",
      "Tilburg",
      "Utrecht"
    ]
  },
  {
    country: "Portugal",
    cities: [
      "Aveiro",
      "Azores",
      "Beja",
      "Braga",
      "Bragança",
      "Castelo Branco",
      "Coimbra",
      "Évora",
      "Faro",
      "Guarda",
      "Leiria",
      "Lisbon",
      "Madeira",
      "Portalegre",
      "Porto",
      "Santarém",
      "Setúbal",
      "Viana do Castelo",
      "Vila Real",
      "Viseu"
    ]
  },
  {
    country: "Spain",
    cities: [
      "A Coruña",
      "Albacete",
      "Alicante",
      "Almería",
      "Andalusia",
      "Araba Álava",
      "Aragon",
      "Badajoz",
      "Balearic Islands",
      "Barcelona",
      "Basque Country",
      "Biscay",
      "Burgos",
      "Cáceres",
      "Cádiz",
      "Canary Islands",
      "Cantabria",
      "Castellón",
      "Castile and León",
      "Castile-La Mancha",
      "Catalonia",
      "Ceuta",
      "Ciudad Real",
      "Community of Madrid",
      "Córdoba",
      "Cuenca",
      "Extremadura",
      "Galicia",
      "Gipuzkoa",
      "Girona",
      "Granada",
      "Guadalajara",
      "Huelva",
      "Huesca",
      "Jaén",
      "La Rioja",
      "Las Palmas",
      "León",
      "Lleida",
      "Lugo",
      "Madrid",
      "Málaga",
      "Melilla",
      "Murcia",
      "Navarre",
      "Ourense",
      "Palencia",
      "Pontevedra",
      "Province of Asturias",
      "Province of Ávila",
      "Region of Murcia",
      "Salamanca",
      "Santa Cruz de Tenerife",
      "Segovia",
      "Seville",
      "Soria",
      "Tarragona",
      "Teruel",
      "Toledo",
      "Valencia",
      "Valencian Community",
      "Valladolid",
      "Zamora",
      "Zaragoza"
    ]
  },
  {
    country: "Sweden",
    cities: [
      "Gothenburg",
      "Malmö",
      "Stockholm",
      "Uppsala",
      "Västerås",
      "Örebro"
    ]
  },
  {
    country: "Switzerland",
    cities: [
      "Basel",
      "Bern",
      "Geneva",
      "Lausanne",
      "Lucerne",
      "Zurich",
      "Winterthur",
      "St. Gallen",
      "Fribourg",
      "Bellinzona"
    ]
  },
  {
    country: "United Kingdom",
    cities: [
      "Aberdeen",
      "Belfast",
      "Birmingham",
      "Bradford",
      "Brighton & Hove",
      "Bristol",
      "Cambridge",
      "Cardiff",
      "Coventry",
      "Derby",
      "Edinburgh",
      "Ely",
      "Glasgow",
      "Leeds",
      "Leicester",
      "Lichfield",
      "Lincoln",
      "Liverpool",
      "London",
      "Manchester",
      "Newcastle",
      "Norwich",
      "Nottingham",
      "Oxford",
      "Plymouth",
      "Portsmouth",
      "Sheffield",
      "Southampton",
      "St Albans",
      "Stoke-on-Trent",
      "Swansea",
      "Truro",
      "Wakefield",
      "Wells",
      "York"
    ]
  }
];
